name: flutter_spotify_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/img_spotify.png
    - assets/images/ic_login_with_google.png
    - assets/images/ic_login_with_facebook.png
    - assets/images/ic_login_with_apple.png
